# Generated by Django 5.1.2 on 2024-10-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tcc_workspace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TCC',
        ),
    ]
