# Generated by Django 5.1.1 on 2024-12-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0007_delete_task'),
        ('app_tcc_workspace', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tcc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_forms.tcc'),
        ),
    ]
