# Generated by Django 5.1.1 on 2024-12-17 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0007_delete_task'),
        ('app_tcc_workspace', '0004_message_tcc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_forms.tcc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
