# Generated by Django 5.1.1 on 2024-12-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0002_alter_tcc_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
