# Generated by Django 5.1.1 on 2024-12-15 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0005_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Descrição padrão'),
        ),
        migrations.AddField(
            model_name='task',
            name='tcc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_forms.tcc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
