# Generated by Django 5.1.1 on 2024-12-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0006_remove_task_created_at_task_description_task_tcc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
